%% DEMO_RUN_PF_IMU_VARSPEED_V8
clear; clc; close all;

rootPath = 'C:\Users\12617\Documents\MATLAB\PF_DS\PF_VARY SPEED';
csvFileName = 'PI5_lstm_pd-20260424-221451.csv';

% Variable-speed segment: 210s to 280s, speed transition 1.25 -> 1.75 -> 0.75.
timeWindow = [210 280];

% Run left and right legs.
legs = {'L','R'};
results = struct();

for i = 1:numel(legs)
    leg = legs{i};

    results.(leg) = run_pf_imu_varspeed_demo_v8(rootPath, csvFileName, leg, ...
        'timeWindow', timeWindow, ...
        'timeColumn', 'Time_ms', ...
        'timeUnit', 'seconds', ...
        'angleUnit', 'deg', ...
        'velocityUnit', 'deg/s', ...
        'useSyncColumns', false, ...
        'useMeasuredVelocity', true, ...
        'downsampleFactor', 1, ...
        ... % preprocessing
        'smoothAngleWindow', 5, ...
        'smoothVelocityWindow', 5, ...
        ... % no acceleration observation in this dataset
        'etaV', 3.0, ...
        'etaA', 0.0, ...
        'etaSign', 2.0, ...
        ... % automatic qstar prior from selected segment
        'useAutoQstarPrior', true, ...
        'priorMarginRatio', 0.10, ...
        ... % PF
        'numParticles', 900, ...
        'Amin', -35.0, ...
        'Amax', -0.1, ...
        'sigmaA', 0.25, ...
        'sigmaQstar', 0.004, ...
        'pSwitch', 0.003, ...
        'switchEpsDeg', 2.5, ...
        'switchVelThreshDeg', 10.0, ...
        ... % paper-style confidence
        'dConf', 1.5, ...
        'confWindowSec', 0.50, ...
        ... % human-side controller policy:
        ... % tau_exo^h = tau_gc + B(c)*dq_int + D(c)*(dq_int-dq)
        'bMax', 2.0, ...
        'dMax', 1.0, ...
        'bGamma', 1.0, ...
        'dGamma', 1.0, ...
        'tauMax', 25.0, ...
        ... % gravity comp disabled by default because hardware parameters are unknown
        'useGravityComp', false, ...
        'alphaG', 0.0, ...
        'gSin', 0.0, ...
        'gCos', 0.0, ...
        'gBias', 0.0, ...
        ... % plots and save
        'makePlots', true, ...
        'showModeMeans', false, ...
        'savePrefix', sprintf('PF_IMU_varspeed_v8_%s_leg', leg));
end

fprintf('\n=== Summary ===\n');
for i = 1:numel(legs)
    leg = legs{i};
    r = results.(leg);
    fprintf('%s leg | vel RMSE %.4f rad/s (%.2f deg/s) | one-step RMSE %.6f rad (%.4f deg) | sign %.2f%%\n', ...
        leg, r.velRMSE, rad2deg(r.velRMSE), r.oneStepRMSE, rad2deg(r.oneStepRMSE), 100*r.signAgree);
end
